### ISSUE TITLE
Question about new services

### ISSUE THREAD

**Issue by Sparo** [definitely246/social#10]
I used this for Linkedin, and have had to extend for Xing...

so I wanted to contribute to extend this package...

I also had to extend `lusitanian/phpoauthlib`...so how can I merge all that...so others can benefit from that?

**Comment by tabennett** [comment]
The lusitanian package still seems to have many bugs in it.  As a result, so does this package.  We're seriously considering a rewrite of this package so that it uses https://github.com/thephpleague/oauth2-client once it becomes more stable.

**Comment by kdocki** [comment]
@Sparo we are thinking about refactoring social so that we don't rely on lusitanian anymore since we seem to be getting a few weird issues here and there with it that are affecting this package. So I wouldn't advise to do any merging just yet :)

After we get this refactor finished we always welcome contributions too, so thanks for asking. :)

**Comment by kdocki** [comment]
@tabennett jinx, you owe me a coke man.

**Comment by Sparo** [comment]
so it would just be for oauth2? or oauth1 also?
